import type { Metadata } from "next";
import "./globals.css";

import ReactQueryProvider from "@/components/providers/ReactQueryProvider";
import { Geist_Mono, Geist } from "next/font/google";
import Link from "next/link";
import { Button } from "@/components/ui/button";

const inter = Geist({
  variable: "--font-body",
  subsets: ["latin"],
});

const spaceGrotesk = Geist_Mono({
  variable: "--font-heading",
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const navbarLinks = [
  { label: "Products", href: "/products" },
  { label: "Upcycle", href: "/upcycle" },
  // { label: "Mystery Box", href: "/mystery-box" },
  { label: "Fragments", href: "/fragments" },
  { label: "Lookbook", href: "/lookbook" },
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased ${inter.variable} ${spaceGrotesk.variable} `}
      >
        <ReactQueryProvider>
          <nav className="fixed top-0 left-0 w-full z-30 px-8 md:px-16 py-4 bg-black bg-opacity-30 backdrop-blur-md text-white font-body">
            <div className="flex items-center justify-between">
              {/* Logo / Brand */}
              <Button
                asChild
                variant="ghost"
                className="text-2xl font-heading font-bold tracking-wide"
              >
                <Link href="/">Studio Remade.</Link>
              </Button>

              {/* Nav Links */}
              <div className="flex space-x-4">
                {navbarLinks.map(({ label, href }) => (
                  <Button
                    key={label}
                    asChild
                    variant="ghost"
                    className="text-sm md:text-base font-medium tracking-wider hover:text-gray-300 transition-colors duration-200"
                  >
                    <Link href={href}>{label}</Link>
                  </Button>
                ))}
              </div>
            </div>
          </nav>
          <main className="">{children}</main>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
